const ANIMALS = {
    ga: {
      name: "Gà",
      emoji: "🐓",
      price: 100000,
      productTime: 4 * 60 * 60,
      product: "trứng",
      productEmoji: "🥚",
      productPrice: 15000,
      feed: 5000,
      level: 3,
      description: "Gà ta chạy bộ, cho trứng chất lượng cao",
    },
    vit: {
      name: "Vịt",
      emoji: "🦆",
      price: 150000,
      productTime: 5 * 60 * 60,
      product: "trứng vịt",
      productEmoji: "🥚",
      productPrice: 20000,
      feed: 7000,
      level: 5,
      description: "Vịt thả đồng, đẻ trứng vịt dinh dưỡng",
    },
    heo: {
      name: "Heo",
      emoji: "🐷",
      price: 300000,
      productTime: 7 * 60 * 60,
      product: "thịt",
      productEmoji: "🥩",
      productPrice: 55000,
      feed: 15000,
      level: 8,
      description: "Heo đặc sản nuôi thả vườn",
    },
    bo: {
      name: "Bò",
      emoji: "🐄",
      price: 500000,
      productTime: 9 * 60 * 60,
      product: "sữa",
      productEmoji: "🥛",
      productPrice: 80000,
      feed: 22000,
      level: 10,
      description: "Bò sữa cho sữa tươi nguyên chất",
    },
    ca: {
      name: "Cá",
      emoji: "🐟",
      price: 80000,
      productTime: 3 * 60 * 60,
      product: "cá tươi",
      productEmoji: "🐠",
      productPrice: 22000,
      feed: 8000,
      level: 4,
      description: "Cá đồng nuôi trong ao",
    },
  
    de: {
      name: "Dê",
      emoji: "🐐",
      price: 800000,
      productTime: 6 * 60 * 60,
      product: "sữa dê",
      productEmoji: "🥛",
      productPrice: 100000,
      feed: 30000,
      level: 11,
      description: "Dê sữa cao cấp từ vùng núi Tây Bắc",
    },
    ngua: {
      name: "Ngựa",
      emoji: "🐎",
      price: 1200000,
      productTime: 11 * 60 * 60,
      product: "lông ngựa",
      productEmoji: "🧶",
      productPrice: 250000,
      feed: 40000,
      level: 12,
      description: "Ngựa thuần chủng quý hiếm",
    },
    huou: {
      name: "Hươu",
      emoji: "🦌",
      price: 1500000,
      productTime: 13 * 60 * 60,
      product: "nhung hươu",
      productEmoji: "🦴",
      productPrice: 380000,
      feed: 45000,
      level: 13,
      description: "Hươu sao quý hiếm, cho nhung chất lượng cao",
    },
    dan_dieu: {
      name: "Đà điểu",
      emoji: "🦩",
      price: 1800000,
      productTime: 15 * 60 * 60,
      product: "trứng đà điểu",
      productEmoji: "🥚",
      productPrice: 450000,
      feed: 50000,
      level: 14,
      description: "Đà điểu châu Phi, cho trứng siêu lớn",
    },
    ky_lan: {
      name: "Kỳ lân",
      emoji: "🦄",
      price: 5000000,
      productTime: 48 * 60 * 60,
      product: "bột kỳ lân",
      productEmoji: "✨",
      productPrice: 1200000,
      feed: 100000,
      level: 15,
      description: "Sinh vật huyền thoại, cho sản phẩm ma thuật quý hiếm",
    },
  };
  