const CROPS = {
    lua: {
      name: "Lúa",
      emoji: "🌾",
      price: 50000,
      time: 40 * 60,
      yield: 80000,
      exp: 5,
      water: 3,
      level: 1,
      description: "Cây lúa nước truyền thống",
    },
    rau: {
      name: "Rau xanh",
      emoji: "🥬",
      price: 10000,
      time: 15 * 60,
      yield: 18000,
      exp: 2,
      water: 2,
      level: 1,
      description: "Các loại rau xanh: rau muống, rau cải...",
    },
    ca_rot: {
      name: "Cà rốt",
      emoji: "🥕",
      price: 15000,
      time: 20 * 60,
      yield: 25000,
      exp: 3,
      water: 2,
      level: 1,
      description: "Cà rốt nhiều vitamin A",
    },
    dau: {
      name: "Đậu",
      emoji: "🌱",
      price: 20000,
      time: 25 * 60,
      yield: 35000,
      exp: 5,
      water: 2,
      level: 2,
      description: "Các loại đậu: đậu xanh, đậu đen...",
    },
    ngo: {
      name: "Ngô",
      emoji: "🌽",
      price: 25000,
      time: 35 * 60,
      yield: 45000,
      exp: 4,
      water: 3,
      level: 3,
      description: "Ngô ngọt đặc sản miền Trung",
    },
    ca_chua: {
      name: "Cà chua",
      emoji: "🍅",
      price: 30000,
      time: 40 * 60,
      yield: 55000,
      exp: 5,
      water: 3,
      level: 4,
      description: "Cà chua tươi ngọt",
    },
    khoai_tay: {
      name: "Khoai tây",
      emoji: "🥔",
      price: 35000,
      time: 45 * 60,
      yield: 65000,
      exp: 5,
      water: 3,
      level: 5,
      description: "Khoai tây Đà Lạt",
    },
    dua_hau: {
      name: "Dưa hấu",
      emoji: "🍉",
      price: 45000,
      time: 60 * 60,
      yield: 85000,
      exp: 10,
      water: 4,
      level: 6,
      description: "Dưa hấu miền Trung ngọt lịm",
    },
    thanh_long: {
      name: "Thanh Long",
      emoji: "🐉",
      price: 140000,
      time: 80 * 60,
      yield: 130000,
      exp: 12,
      water: 2,
      level: 8,
      description: "Thanh long ruột đỏ đặc sản Việt Nam",
    },
    khoai_lang: {
      name: "Khoai lang",
      emoji: "🍠",
      price: 40000,
      time: 50 * 60,
      yield: 70000,
      exp: 10,
      water: 2,
      level: 7,
      description: "Khoai lang vỏ tím ruột vàng",
    },
  
    ot: {
      name: "Ớt",
      emoji: "🌶️",
      price: 28000,
      time: 35 * 60,
      yield: 50000,
      exp: 9,
      water: 2,
      level: 4,
      description: "Ớt cay nồng đặc trưng của ẩm thực Việt Nam",
    },
    sa: {
      name: "Sả",
      emoji: "🌿",
      price: 32000,
      time: 40 * 60,
      yield: 58000,
      exp: 5,
      water: 3,
      level: 4,
      description: "Sả thơm dùng trong nhiều món ăn truyền thống",
    },
    dua_leo: {
      name: "Dưa leo",
      emoji: "🥒",
      price: 38000,
      time: 30 * 60,
      yield: 62000,
      exp: 6,
      water: 4,
      level: 5,
      description: "Dưa leo mát lành, trồng nhanh thu hoạch nhanh",
    },
  
    gung: {
      name: "Gừng",
      emoji: "🌱",
      price: 50000,
      time: 55 * 60,
      yield: 90000,
      exp: 7,
      water: 2,
      level: 6,
      description: "Gừng ấm nồng, đặc sản vùng đất Trà Quế",
    },
    mia: {
      name: "Mía",
      emoji: "🎋",
      price: 60000,
      time: 70 * 60,
      yield: 110000,
      exp: 8,
      water: 5,
      level: 6,
      description: "Mía ngọt từ đồng bằng sông Cửu Long",
    },
    cai_thao: {
      name: "Cải thảo",
      emoji: "🥬",
      price: 55000,
      time: 65 * 60,
      yield: 100000,
      exp: 9,
      water: 4,
      level: 7,
      description: "Cải thảo tươi ngon từ vùng cao nguyên",
    },
  
    ca_phe: {
      name: "Cà phê",
      emoji: "☕",
      price: 150000,
      time: 100 * 60,
      yield: 280000,
      exp: 15,
      water: 3,
      level: 8,
      description: "Cà phê Robusta thơm ngon từ Tây Nguyên",
    },
    tieu: {
      name: "Tiêu",
      emoji: "⚫",
      price: 180000,
      time: 90 * 60,
      yield: 320000,
      exp: 18,
      water: 2,
      level: 9,
      description: "Hạt tiêu Phú Quốc nổi tiếng thế giới",
    },
    tra: {
      name: "Trà",
      emoji: "🍵",
      price: 200000,
      time: 120 * 60,
      yield: 400000,
      exp: 35,
      water: 4,
      level: 10,
      description: "Trà Shan tuyết từ vùng núi cao Tây Bắc",
    },
  
    chuoi: {
      name: "Chuối",
      emoji: "🍌",
      price: 70000,
      time: 75 * 60,
      yield: 130000,
      exp: 12,
      water: 3,
      level: 7,
      description: "Chuối tiêu thơm ngon từ miền Tây Nam Bộ",
    },
    xoai: {
      name: "Xoài",
      emoji: "🥭",
      price: 120000,
      time: 85 * 60,
      yield: 220000,
      exp: 10,
      water: 3,
      level: 8,
      description: "Xoài cát Hòa Lộc ngọt lịm",
    },
    vai: {
      name: "Vải",
      emoji: "🔴",
      price: 160000,
      time: 95 * 60,
      yield: 290000,
      exp: 22,
      water: 4,
      level: 9,
      description: "Vải thiều Lục Ngạn chín mọng",
    },
    buoi: {
      name: "Bưởi",
      emoji: "🟢",
      price: 190000,
      time: 110 * 60,
      yield: 350000,
      exp: 20,
      water: 4,
      level: 9,
      description: "Bưởi Năm Roi thơm ngon, ngọt lịm",
    },
    dua: {
      name: "Dừa",
      emoji: "🥥",
      price: 210000,
      time: 120 * 60,
      yield: 420000,
      exp: 25,
      water: 2,
      level: 10,
      description: "Dừa Bến Tre nổi tiếng với nước ngọt thơm mát",
    },
    nho_do: {
      name: "Nho đỏ",
      emoji: "🍇",
      price: 250000,
      time: 130 * 60,
      yield: 480000,
      exp: 50,
      water: 5,
      level: 11,
      description: "Nho đỏ quý hiếm từ vùng cao Đà Lạt",
    },
    sen: {
      name: "Hoa sen",
      emoji: "🪷",
      price: 300000,
      time: 140 * 60,
      yield: 590000,
      exp: 40,
      water: 6,
      level: 12,
      description: "Hoa sen quý, biểu tượng của sự tinh khiết",
    },
    lan: {
      name: "Lan đột biến",
      emoji: "🌸",
      price: 500000,
      time: 180 * 60,
      yield: 1200000,
      exp: 50,
      water: 4,
      level: 13,
      description: "Lan đột biến cực hiếm, giá trị cực cao",
    },
    sam: {
      name: "Nhân sâm",
      emoji: "🌿",
      price: 800000,
      time: 240 * 60,
      yield: 1800000,
      exp: 60,
      water: 5,
      level: 14,
      description: "Nhân sâm quý hiếm nghìn năm tuổi",
    },
    truffle: {
      name: "Nấm Truffle",
      emoji: "🍄",
      price: 1200000,
      time: 300 * 60,
      yield: 3000000,
      exp: 70,
      water: 4,
      level: 15,
      description: "Nấm truffle đen - thực phẩm đắt giá nhất thế giới",
    },
  };