const PROCESSING_RECIPES = {
    banh_mi: {
      name: "Bánh mì",
      emoji: "🥖",
      ingredients: { lúa: 3 },
      yield: 1,
      value: 100000,
      exp: 15,
      time: 15 * 60,
      level: 3,
      description: "Bánh mì mềm thơm từ lúa xay thành bột",
    },
    pho_mai: {
      name: "Phô mai",
      emoji: "🧀",
      ingredients: { sữa: 3 },
      yield: 1,
      value: 300000,
      exp: 20,
      time: 30 * 60,
      level: 5,
      description: "Phô mai được làm từ sữa bò tươi ngon",
    },
    trung_bac: {
      name: "Trứng bác",
      emoji: "🍳",
      ingredients: { trứng: 2, "trứng vịt": 1 },
      yield: 1,
      value: 60000,
      exp: 10,
      time: 10 * 60,
      level: 2,
      description: "Món trứng chiên thơm ngon bổ dưỡng",
    },
    xuc_xich: {
      name: "Xúc xích",
      emoji: "🌭",
      ingredients: { thịt: 2 },
      yield: 3,
      value: 150000,
      exp: 18,
      time: 20 * 60,
      level: 4,
      description: "Xúc xích thịt heo ngon tuyệt",
    },
    ca_kho: {
      name: "Cá kho",
      emoji: "🐟",
      ingredients: { "cá tươi": 3 },
      yield: 2,
      value: 70000,
      exp: 12,
      time: 15 * 60,
      level: 2,
      description: "Cá kho tộ đậm đà hương vị Việt Nam",
    },
    salad: {
      name: "Salad",
      emoji: "🥗",
      ingredients: { "rau xanh": 3, "cà rốt": 2 },
      yield: 3,
      value: 80000,
      exp: 15,
      time: 10 * 60,
      level: 3,
      description: "Salad rau củ tươi ngon bổ dưỡng",
    },
    thit_kho: {
      name: "Thịt kho",
      emoji: "🍲",
      ingredients: { thịt: 3, trứng: 2 },
      yield: 3,
      value: 200000,
      exp: 25,
      time: 30 * 60,
      level: 6,
      description: "Thịt kho tàu đậm đà, béo ngậy",
    },
    banh_ngot: {
      name: "Bánh ngọt",
      emoji: "🍰",
      ingredients: { trứng: 3, sữa: 2, lúa: 2 },
      yield: 2,
      value: 180000,
      exp: 20,
      time: 20 * 60,
      level: 7,
      description: "Bánh ngọt mềm mịn thơm ngon",
    },
  };