 
  const SHOP_ITEMS = {
    phan_bon: {
      name: "Phân bón",
      emoji: "💩",
      price: 1000000,
      description: "Giảm 20% thời gian trồng trọt",
      effect: "grow_boost",
      duration: 24 * 60 * 60 * 1000,
      level: 1,
    },
    thuoc_sau: {
      name: "Thuốc sâu",
      emoji: "🧪",
      price: 3000000,
      description: "Tăng 20% sản lượng thu hoạch",
      effect: "yield_boost",
      duration: 24 * 60 * 60 * 1000,
      level: 3,
    },
    may_cay: {
      name: "Máy cày",
      emoji: "🚜",
      price: 50000000,
      description: "Tự động gieo trồng vụ mới sau thu hoạch",
      effect: "auto_plant",
      duration: null,
      level: 9,
    },
    he_thong_tuoi: {
      name: "Hệ thống tưới",
      emoji: "💧",
      price: 50000000,
      description: "Tự động tưới cây mỗi 4 giờ",
      effect: "auto_water",
      duration: null,
      level: 7,
    },
    chuong_trai: {
      name: "Nâng Cấp Chuồng trại",
      emoji: "🏡",
      price: 10000000,
      description: "Tăng số lượng vật nuôi tối đa lên 10",
      effect: "animal_capacity",
      duration: null,
      level: 9,
    },
    chuong_trai_1: {
      name: "Chuồng trại cấp 1",
      emoji: "🏡",
      price: 20000000,
      description: "Tăng số lượng vật nuôi tối đa lên 15",
      effect: "animal_capacity_1",
      duration: null,
      level: 9,
    },
    chuong_trai_2: {
      name: "Chuồng trại cấp 2",
      emoji: "🏘️",
      price: 60000000,
      description: "Tăng số lượng vật nuôi tối đa lên 25 con",
      effect: "animal_capacity_2",
      duration: null,
      level: 9,
    },
    chuong_trai_3: {
      name: "Trang trại hiện đại",
      emoji: "🏰",
      price: 150000000,
      description: "Tăng số lượng vật nuôi tối đa lên 40 con",
      effect: "animal_capacity_3",
      duration: null,
      level: 12,
    },
    thuc_an_gia_suc: {
      name: "Thức ăn gia súc",
      emoji: "🌾",
      price: 5000000,
      description: "Tăng 30% sản lượng từ vật nuôi",
      effect: "animal_boost",
      duration: 24 * 60 * 60 * 1000,
      level: 4,
    },
    giong_cao_cap: {
      name: "Giống cây cao cấp",
      emoji: "🌱",
      price: 1000000,
      description: "Tăng 50% kinh nghiệm từ trồng trọt",
      effect: "exp_boost",
      duration: 24 * 60 * 60 * 1000,
      level: 4,
    },
  };
  